# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.0].define(version: 2023_09_12_202021) do
  create_table "incidents", force: :cascade do |t|
    t.string "sys_id"
    t.string "number"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "parent"
    t.string "made_sla"
    t.string "caused_by"
    t.string "watch_list"
    t.string "upon_reject"
    t.datetime "sys_updated_on"
    t.string "child_incidents"
    t.string "hold_reason"
    t.string "origin_table"
    t.string "task_effective_number"
    t.string "approval_history"
    t.string "sys_updated_by"
    t.string "opened_by"
    t.string "user_input"
    t.datetime "sys_created_on"
    t.string "sys_domain"
    t.integer "state"
    t.string "route_reason"
    t.string "sys_created_by"
    t.string "knowledge"
    t.string "order"
    t.string "calendar_stc"
    t.datetime "closed_at"
    t.string "cmdb_ci"
    t.string "delivery_plan"
    t.string "contract"
    t.integer "impact"
    t.string "active"
    t.string "work_notes_list"
    t.string "business_service"
    t.string "business_impact"
    t.integer "priority"
    t.string "sys_domain_path"
    t.string "rfc"
    t.string "time_worked"
    t.datetime "expected_start"
    t.datetime "opened_at"
    t.datetime "business_duration"
    t.string "group_list"
    t.string "work_end"
    t.string "caller_id"
    t.datetime "reopened_time"
    t.datetime "resolved_at"
    t.string "approval_set"
    t.string "subcategory"
    t.string "work_notes"
    t.string "universal_request"
    t.string "short_description"
    t.string "close_code"
    t.string "correlation_display"
    t.string "delivery_task"
    t.string "work_start"
    t.string "assignment_group"
    t.string "additional_assignee_list"
    t.integer "business_stc"
    t.string "cause"
    t.string "description"
    t.string "origin_id"
    t.datetime "calendar_duration"
    t.string "close_notes"
    t.integer "notify"
    t.string "service_offering"
    t.string "sys_class_name"
    t.string "closed_by"
    t.string "follow_up"
    t.string "parent_incident"
    t.string "contact_type"
    t.string "reopened_by"
    t.integer "incident_state"
    t.integer "urgency"
    t.string "problem_id"
    t.string "company"
    t.integer "reassignment_count"
    t.datetime "activity_due"
    t.string "assigned_to"
    t.integer "severity"
    t.string "comments"
    t.string "approval"
    t.string "sla_due"
    t.string "comments_and_work_notes"
    t.integer "due_date"
    t.integer "sys_mod_count"
    t.integer "reopen_count"
    t.string "sys_tags"
    t.integer "escalation"
    t.string "upon_approval"
    t.integer "correlation_id"
    t.string "location"
    t.string "category"
    t.string "resolved_by"
  end

end
