class AddParamsToIncidents < ActiveRecord::Migration[7.0]
  def change
    add_column :incidents, :parent, :string, default: nil
    add_column :incidents, :made_sla, :string, default: nil
    add_column :incidents, :caused_by, :string, default: nil
    add_column :incidents, :watch_list, :string, default: nil
    add_column :incidents, :upon_reject, :string, default: nil
    add_column :incidents, :sys_updated_on, :timestamp, default: nil
    add_column :incidents, :child_incidents, :string, default: nil
    add_column :incidents, :hold_reason, :string, default: nil
    add_column :incidents, :origin_table, :string, default: nil
    add_column :incidents, :task_effective_number, :string, default: nil
    add_column :incidents, :approval_history, :string, default: nil
    add_column :incidents, :sys_updated_by, :string, default: nil
    add_column :incidents, :opened_by, :string, default: nil
    add_column :incidents, :user_input, :string, default: nil
    add_column :incidents, :sys_created_on, :timestamp, default: nil
    add_column :incidents, :sys_domain, :string, default: nil
    add_column :incidents, :state, :integer, default: nil
    add_column :incidents, :route_reason, :string, default: nil
    add_column :incidents, :sys_created_by, :string, default: nil
    add_column :incidents, :knowledge, :string, default: nil
    add_column :incidents, :order, :string, default: nil
    add_column :incidents, :calendar_stc, :string, default: nil
    add_column :incidents, :closed_at, :timestamp, default: nil
    add_column :incidents, :cmdb_ci, :string, default: nil
    add_column :incidents, :delivery_plan, :string, default: nil
    add_column :incidents, :contract, :string, default: nil
    add_column :incidents, :impact, :integer, default: nil
    add_column :incidents, :active, :string, default: nil
    add_column :incidents, :work_notes_list, :string, default: nil
    add_column :incidents, :business_service, :string, default: nil
    add_column :incidents, :business_impact, :string, default: nil
    add_column :incidents, :priority, :integer, default: nil
    add_column :incidents, :sys_domain_path, :string, default: nil
    add_column :incidents, :rfc, :string, default: nil
    add_column :incidents, :time_worked, :string, default: nil
    add_column :incidents, :expected_start, :timestamp, default: nil
    add_column :incidents, :opened_at, :timestamp, default: nil
    add_column :incidents, :business_duration, :timestamp, default: nil
    add_column :incidents, :group_list, :string, default: nil
    add_column :incidents, :work_end, :string, default: nil
    add_column :incidents, :caller_id, :string, default: nil
    add_column :incidents, :reopened_time, :timestamp, default: nil
    add_column :incidents, :resolved_at, :timestamp, default: nil
    add_column :incidents, :approval_set, :string, default: nil
    add_column :incidents, :subcategory, :string, default: nil
    add_column :incidents, :work_notes, :string, default: nil
    add_column :incidents, :universal_request, :string, default: nil
    add_column :incidents, :short_description, :string, default: nil
    add_column :incidents, :close_code, :string, default: nil
    add_column :incidents, :correlation_display, :string, default: nil
    add_column :incidents, :delivery_task, :string, default: nil
    add_column :incidents, :work_start, :string, default: nil
    add_column :incidents, :assignment_group, :string, default: nil
    add_column :incidents, :additional_assignee_list, :string, default: nil
    add_column :incidents, :business_stc, :integer, default: nil
    add_column :incidents, :cause, :string, default: nil
    add_column :incidents, :description, :string, default: nil
    add_column :incidents, :origin_id, :string, default: nil
    add_column :incidents, :calendar_duration, :timestamp, default: nil
    add_column :incidents, :close_notes, :string, default: nil
    add_column :incidents, :notify, :integer, default: nil
    add_column :incidents, :service_offering, :string, default: nil
    add_column :incidents, :sys_class_name, :string, default: nil
    add_column :incidents, :closed_by, :string, default: nil
    add_column :incidents, :follow_up, :string, default: nil
    add_column :incidents, :parent_incident, :string, default: nil
    add_column :incidents, :contact_type, :string, default: nil
    add_column :incidents, :reopened_by, :string, default: nil
    add_column :incidents, :incident_state, :integer, default: nil
    add_column :incidents, :urgency, :integer, default: nil
    add_column :incidents, :problem_id, :string, default: nil
    add_column :incidents, :company, :string, default: nil
    add_column :incidents, :reassignment_count, :integer, default: nil
    add_column :incidents, :activity_due, :timestamp, default: nil
    add_column :incidents, :assigned_to, :string, default: nil
    add_column :incidents, :severity, :integer, default: nil
    add_column :incidents, :comments, :string, default: nil
    add_column :incidents, :approval, :string, default: nil
    add_column :incidents, :sla_due, :string, default: nil
    add_column :incidents, :comments_and_work_notes, :string, default: nil
    add_column :incidents, :due_date, :integer, default: nil
    add_column :incidents, :sys_mod_count, :integer, default: nil
    add_column :incidents, :reopen_count, :integer, default: nil
    add_column :incidents, :sys_tags, :string, default: nil
    add_column :incidents, :escalation, :integer, default: nil
    add_column :incidents, :upon_approval, :string, default: nil
    add_column :incidents, :correlation_id, :integer, default: nil
    add_column :incidents, :location, :string, default: nil
    add_column :incidents, :category, :string, default: nil
  end
end
